### ISSUE TITLE
请问一下作者大大，这个编辑器的exe文件在musicpy仓库的release里没有呀，能否麻烦作者上传一下呢？

### ISSUE THREAD

**Issue by ferry-hhh** [Rainbow-Dreamer/musicpy_editor#1]
我因为装了conda的原因一直无法用pythonw打开那个.pyw文件。谢谢作者！

**Comment by Rainbow-Dreamer** [comment]
conda把需要安装的库都安装好应该就可以打开了。exe文件的编译由于依赖库太多，编译后体积非常庞大，而且每次依赖库musicpy和sf2_loader稍微改动就需要重新编译很费时间，因此现在的版本中已经不使用编译文件了，也可以跨平台运行。
